
BEGIN;

CREATE TABLE token (
    id SERIAL PRIMARY KEY,
    account_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (account_id) REFERENCES "account" (id) ON DELETE CASCADE
);

END;
